version: '3.8'
services:
  movies:
    image: sreevanga/popupmovies:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
    volumes:
      - movies
  train:
    image: sreevanga/popuptrain:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
    volumes:
      - train
  dth:
    image: sreevanga/popupdth:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
    volumes:
      - dth
  recharge:
    image: sreevanga/popuprecharge:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3
    volumes:
      - recharge
